config/routes.rb
Rails.application.routes.draw do
  root 'pages#stuk_todo_home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/stuk_todo_home', path: 'stuk_todo', as: 'stuk_todo'
  get 'pages/estuk_home', path: 'estuk', as: 'estuk'
  get 'pages/stuk_starter_home', path: 'stuk_starter', as: 'stuk_starter'
  get 'pages/stuk_places_home', path: 'stuk_places', as: 'stuk_places'

  resources :stuk_todo_tasks do
    member do
      put :change
    end
  end

  resources :stuk_books
  get 'estuk_dashboard' => 'pages#estuk_dashboard'
  post '/buy/:slug', to: 'estuk_transactions#create', as: :buy
  get '/pickup/:guid', to: 'estuk_transactions#pickup', as: :pickup
  
  resources :stuk_starter_projects do
    resources :stuk_starter_rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :stuk_starter_pledges
    resources :stuk_starter_payments, only: [:new, :create]
  end

  resources :places
  resources :places_reviews
  get 'stuk_places_dashboard' => 'pages#stuk_places_dashboard'

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/models/stuk_todo_task.rb
class StukTodoTask < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user_id, :content

  auto_html_for :content do
    html_escape
    image
    youtube(width: '100%', height: 250)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end
end

app/controllers/stuk_todo_tasks_controller.rb
class StukTodoTasksController < ApplicationController
  before_action :set_stuk_todo_task, only: [:show, :edit, :update, :destroy, :change]
  before_action :authenticate_user!

  # GET /stuk_todo_tasks
  # GET /stuk_todo_tasks.json
  def index
    @to_do = current_user.stuk_todo_tasks.where(state: 'to_do')
    @doing = current_user.stuk_todo_tasks.where(state: 'doing')
    @done = current_user.stuk_todo_tasks.where(state: 'done')
  end

  # GET /stuk_todo_tasks/1
  # GET /stuk_todo_tasks/1.json
  def show
  end

  # GET /stuk_todo_tasks/new
  def new
    @stuk_todo_task = StukTodoTask.new
  end

  # GET /stuk_todo_tasks/1/edit
  def edit
  end

  # POST /stuk_todo_tasks
  # POST /stuk_todo_tasks.json
  def create
    @stuk_todo_task = current_user.stuk_todo_tasks.new(stuk_todo_task_params)

    respond_to do |format|
      if @stuk_todo_task.save
        format.html { redirect_to @stuk_todo_task, notice: 'Stuk todo task was successfully created.' }
        format.json { render :show, status: :created, location: @stuk_todo_task }
      else
        format.html { render :new }
        format.json { render json: @stuk_todo_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuk_todo_tasks/1
  # PATCH/PUT /stuk_todo_tasks/1.json
  def update
    respond_to do |format|
      if @stuk_todo_task.update(stuk_todo_task_params)
        format.html { redirect_to @stuk_todo_task, notice: 'Stuk todo task was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuk_todo_task }
      else
        format.html { render :edit }
        format.json { render json: @stuk_todo_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuk_todo_tasks/1
  # DELETE /stuk_todo_tasks/1.json
  def destroy
    @stuk_todo_task.destroy
    respond_to do |format|
      format.html { redirect_to stuk_todo_tasks_url, notice: 'Stuk todo task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change
    @stuk_todo_task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html { redirect_to stuk_todo_tasks_path, notice: 'Task status successfully changed!' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuk_todo_task
      @stuk_todo_task = StukTodoTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuk_todo_task_params
      params.require(:stuk_todo_task).permit(:content, :state)
    end
end

app/views/stuk_todo_tasks/_form.html.slim
= simple_form_for(@stuk_todo_task, html: { class: 'form-signin' }) do |f|
  = f.error_notification
  = f.input :content, label: false, autofocus: true, placeholder: 'Content', required: true
  = f.button :submit, 'Submit', class: 'btn btn-lg btn-primary btn-block'

app/views/stuk_todo_tasks/_stuk_todo_task.html.slim
.panel.panel-info
  .panel-heading
    = link_to edit_stuk_todo_task_path(stuk_todo_task) do
      |Created 
      = time_ago_in_words(stuk_todo_task.created_at)
      |  ago
    = link_to 'X', stuk_todo_tasks_path(stuk_todo_task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'pull-right'
  .panel-body = raw(stuk_todo_task.content)
  .panel-footer.text-center
    .btn-group.btn-group-justified
      - if stuk_todo_task.state == 'doing'
        = link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_stuk_todo_task_path(stuk_todo_task, state: 'to_do'), method: :put, class: 'btn btn-info btn-md btn-block'
        = link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_stuk_todo_task_path(stuk_todo_task, state: 'done'), method: :put, class: 'btn btn-info btn-md btn-block'
      - elsif stuk_todo_task.state == 'done'
        = link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_stuk_todo_task_path(stuk_todo_task, state: 'doing'), method: :put, class: 'btn btn-info btn-md btn-block'
      - else
        = link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_stuk_todo_task_path(stuk_todo_task, state: 'doing'), method: :put, class: 'btn btn-info btn-md btn-block'

app/views/stuk_todo_tasks/edit.html.slim
h1.text-center Editing Task

== render 'form'

= link_to 'Show', @stuk_todo_task
'|
= link_to 'Back', stuk_todo_tasks_path

app/views/stuk_todo_tasks/index.html.slim
p#notice = notice

.row
  .col-md-4
    h1.text-center Todo
    = render @to_do

  .col-md-4
    h1.text-center Doing
    = render @doing

  .col-md-4
    h1.text-center Done
    = render @done


br

= link_to 'New Stuk todo task', new_stuk_todo_task_path

app/views/stuk_todo_tasks/new.html.slim
h1.text-center New Task

== render 'form'

= link_to 'Back', stuk_todo_tasks_path

app/views/stuk_todo_tasks/show.html.slim
p#notice = notice

p
  strong Content:
  = @stuk_todo_task.content

p
  strong State:
  = @stuk_todo_task.state

= link_to 'Edit', edit_stuk_todo_task_path(@stuk_todo_task)
'|
= link_to 'Back', stuk_todo_tasks_path