config/routes.rb
Rails.application.routes.draw do
  root 'pages#stuk_todo_home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/stuk_todo_home', path: 'stuk_todo', as: 'stuk_todo'
  get 'pages/estuk_home', path: 'estuk', as: 'estuk'
  get 'pages/stuk_starter_home', path: 'stuk_starter', as: 'stuk_starter'
  get 'pages/stuk_places_home', path: 'stuk_places', as: 'stuk_places'

  resources :stuk_todo_tasks do
    member do
      put :change
    end
  end

  resources :stuk_books
  get 'estuk_dashboard' => 'pages#estuk_dashboard'
  post '/buy/:slug', to: 'estuk_transactions#create', as: :buy
  get '/pickup/:guid', to: 'estuk_transactions#pickup', as: :pickup
  
  resources :stuk_starter_projects do
    resources :stuk_starter_rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :stuk_starter_pledges
    resources :stuk_starter_payments, only: [:new, :create]
  end

  resources :places
  resources :places_reviews
  get 'stuk_places_dashboard' => 'pages#stuk_places_dashboard'

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/views/pages/_estuk_books.html.slim
table.table.table-condensed
  thead
    tr
      th ID
      th Name
      th Available
      th
  tbody
    - @stuk_books.each do |book|
      tr
        td #{book.id}
        td = link_to book.name, stuk_book_path(book)
        td #{book.availability}
        td = link_to 'Edit', edit_stuk_book_path(book)

app/views/pages/_estuk_purchased.html.slim
table.table.table-condensed
  thead
    tr
      th Name
      th Date
  tbody
    - @purchased.each do |sale|
      tr
        td = link_to sale.stuk_book.name, pickup_path(sale.guid)
        td #{time_ago_in_words(sale.created_at)} ago

app/views/pages/_estuk_sales.html.slim
table.table.table-condensed
  thead
    tr
      th Name
      th Date
      th Buyer
  tbody
    - @sales.each do |sale|
      tr
        td = link_to sale.stuk_book.name, pickup_path(sale.guid)
        td #{time_ago_in_words(sale.created_at)} ago
        td #{sale.buyer_email}

app/views/pages/about.html.slim
h1 About
h3 Our mission is to improve productivity.

app/views/pages/estuk_dashboard.html.slim
.row
  h1.text-center Dashboard
  .col-md-4
    h3.text-center = link_to 'New Book', new_stuk_book_path, class: 'btn btn-primary btn-sm'
    = render 'estuk_books'
  .col-md-4
    h3.text-center Purchased
    = render 'estuk_purchased'
  .col-md-4
    h3.text-center Sales
    = render 'estuk_sales'

app/views/pages/estuk_home.html.slim
.jumbotron
  h1 Welcome to our store
  p The largest online Digital Books Store

  = link_to 'Books', stuk_books_path, class: 'btn btn-primary'
  = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary'

  .row
    = render @stuk_books

app/views/pages/home.html.slim
.jumbotron
  h1 
    i.fa.fa-circle-o-notch
    |  Stukdo
  p This is my smart To Do app, made with Ruby on Rails
  = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg'

app/views/pages/stuk_places_dashboard.html.slim
.row
  .col-md-2
    h3 = @user.name
    = gravatar_tag @user.email, size: 150
  .col-md-5
    h3 My Places
    table.table
      thead
        tr
          th Name
          th Created
          th
      tbody
        - @places.each do |place|
          tr
            td = place.name
            td #{time_ago_in_words(place.created_at)} ago
            td #{link_to 'edit', edit_place_path(place)} | #{link_to 'delete', place_path(place), method: :delete}
  .col-md-5
    h3 My Reviews
    table.table
      thead
        tr
          th Place
          th When
          th Rating
      tbody
        - @places_reviews.each do |review|
          tr
            td = review.place.name
            td #{time_ago_in_words(review.created_at)} ago
            td[class="score_#{review.id}"]
            td #{link_to 'edit', edit_places_review_path(review)} | #{link_to 'delete', places_review_path(review), method: :delete}

- @places_reviews.each do |review|
  javascript:
    $(".score_#{review.id}").raty({
      starOn: "#{{image_path('star-on.png')}}",
      starOff: "#{{image_path('star-off.png')}}",
      score: "#{review.score}",
      readOnly: true
    });

app/views/pages/stuk_places_home.html.slim
.text-center.landing_title
  = link_to "Find places you'll fall in love with!", places_path, class: 'btn btn-default btn-lg btn-landing'

app/views/pages/stuk_starter_home.html.slim
- if @displayed_projects.any?
  = render 'stuk_starter_projects/stuk_starter_carousel', stuk_starter_projects: @displayed_projects

  .container
    br:br:br
    h3.project-subtitle Our Project
    .row
      = render @stuk_starter_projects

- else
  .container.text-center
    br:br:br
    h2 Create your first project
    = link_to 'Start Project!', new_stuk_starter_project_path, class: 'btn btn-success btn-lg'

app/views/pages/stuk_to_do_home.html.slim
.jumbotron
  h1 
    i.fa.fa-circle-o-notch
    |  Stukdo
  p This is my smart To Do app, made with Ruby on Rails
  = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg'

app/views/pages/stuk_todo_home.html.slim
.jumbotron
  h1 
    i.fa.fa-circle-o-notch
    |  Stukdo
  p This is my smart To Do app, made with Ruby on Rails
  = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg'

app/views/pages/stukstarter_home.html.slim
- if @displayed_projects.any?
  = render 'stuk_starter_carousel'

  .container
    br:br:br
    h3.project-subtitle Our Project
    .row
      = render @stuk_starter_projects

- else
  .container.text-center
    br:br:br
    h2 Create your first project
    = link_to 'Start Project!', '#', class: 'btn btn-success btn-lg'