config/routes.rb
Rails.application.routes.draw do
  root 'pages#stuk_todo_home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/stuk_todo_home', path: 'stuk_todo', as: 'stuk_todo'
  get 'pages/estuk_home', path: 'estuk', as: 'estuk'
  get 'pages/stuk_starter_home', path: 'stuk_starter', as: 'stuk_starter'
  get 'pages/stuk_places_home', path: 'stuk_places', as: 'stuk_places'

  resources :stuk_todo_tasks do
    member do
      put :change
    end
  end

  resources :stuk_books
  get 'estuk_dashboard' => 'pages#estuk_dashboard'
  post '/buy/:slug', to: 'estuk_transactions#create', as: :buy
  get '/pickup/:guid', to: 'estuk_transactions#pickup', as: :pickup
  
  resources :stuk_starter_projects do
    resources :stuk_starter_rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :stuk_starter_pledges
    resources :stuk_starter_payments, only: [:new, :create]
  end

  resources :places
  resources :places_reviews
  get 'stuk_places_dashboard' => 'pages#stuk_places_dashboard'

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/models/stuk_book.rb
class StukBook < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :e_stuk_sales

  validates_numericality_of :price, greater_than: 49, message: 'Must be at least 50 cents'
  
  scope :available, -> { where(availability: true) }

  mount_uploader :image, StukBookImageUploader
  mount_uploader :resource, StukBookResourceUploader
end

app/controllers/stuk_books_controller.rb
class StukBooksController < ApplicationController
  before_action :set_stuk_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /stuk_books
  # GET /stuk_books.json
  def index
    @stuk_books = StukBook.available
  end

  # GET /stuk_books/1
  # GET /stuk_books/1.json
  def show
  end

  # GET /stuk_books/new
  def new
    @stuk_book = StukBook.new
  end

  # GET /stuk_books/1/edit
  def edit
    authorize! :manage, @stuk_book
  end

  # POST /stuk_books
  # POST /stuk_books.json
  def create
    @stuk_book = current_user.stuk_books.new(stuk_book_params)

    respond_to do |format|
      if @stuk_book.save
        format.html { redirect_to @stuk_book, notice: 'Stuk book was successfully created.' }
        format.json { render :show, status: :created, location: @stuk_book }
      else
        format.html { render :new }
        format.json { render json: @stuk_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuk_books/1
  # PATCH/PUT /stuk_books/1.json
  def update
    authorize! :manage, @stuk_book

    respond_to do |format|
      if @stuk_book.update(stuk_book_params)
        format.html { redirect_to @stuk_book, notice: 'Stuk book was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuk_book }
      else
        format.html { render :edit }
        format.json { render json: @stuk_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuk_books/1
  # DELETE /stuk_books/1.json
  def destroy
    authorize! :manage, @stuk_book

    @stuk_book.destroy
    respond_to do |format|
      format.html { redirect_to stuk_books_url, notice: 'Stuk book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuk_book
      @stuk_book = StukBook.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuk_book_params
      params.require(:stuk_book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/views/stuk_books/_form.html.slim
= simple_form_for(@stuk_book, html: { class: 'form-signin' }) do |f|
  = f.error_notification

  = f.input :name, required: true, label: false, placeholder: 'Name', input_html: { class: 'form-control' }
  = f.input :author, required: true, label: false, placeholder: 'Author', input_html: { class: 'form-control' }
  = f.input :description, required: true, label: false, placeholder: 'Description', input_html: { class: 'form-control' }, rows: 5
  br
  = f.input :price, required: true, label: false, placeholder: 'Price', input_html: { class: 'form-control' }

  = f.input :image
  = f.input :resource

  .checkbox.text-center
    p Availability
    = f.input :availability, required: false, label: false

  = f.button :submit, 'Submit', class: 'btn btn-primary btn-block'

app/views/stuk_books/_purchased.html.slim
table.table.table-condensed
  thead
    tr
      th Name
      th Date
  tbody
    - @purchased.each do |sale|
      tr
        td = link_to sale.stuk_book.name, pickup_path(sale.guid)
        td #{time_ago_in_words(sale.created_at)} ago
        

app/views/stuk_books/_stuk_book.html.slim
.col-md-3
  .thumbnail
    = link_to stuk_book_path(stuk_book) do
      = image_tag stuk_book.image_url, class: 'img-responsive'

  .caption
    p:strong = stuk_book.name
    p $#{stuk_book.price.to_f / 100}

app/views/stuk_books/edit.html.slim
h1.text-center Editing Book

== render 'form'

= link_to 'Show', @stuk_book
'|
= link_to 'Back', stuk_books_path

app/views/stuk_books/index.html.slim
.row
  = render @stuk_books

app/views/stuk_books/new.html.slim
h1.text-center New Book

== render 'form'

= link_to 'Back', stuk_books_path

app/views/stuk_books/show.html.slim
.container
  .row
    .col-md-6
      = image_tag @stuk_book.image_url, class: 'img-responsive'
    .col-md-6
      h3 #{@stuk_book.name} by #{@stuk_book.author}
      p.justify #{@stuk_book.description}
      h4.text-right $#{@stuk_book.price.to_f / 100}

      - if current_user
        = form_tag buy_path(slug: @stuk_book.slug) do
          script[src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="#{Rails.configuration.stripe[:publishable_key]}" data-amount="#{@stuk_book.price}" data-name="eRangki" data-description="#{@stuk_book.name}" data-email="#{current_user.email}" data-locale="auto"]
      - else
        p Please login first to Buy