config/routes.rb
Rails.application.routes.draw do
  root 'pages#stuk_todo_home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'pages/stuk_todo_home', path: 'stuk_todo', as: 'stuk_todo'
  get 'pages/estuk_home', path: 'estuk', as: 'estuk'
  get 'pages/stuk_starter_home', path: 'stuk_starter', as: 'stuk_starter'
  get 'pages/stuk_places_home', path: 'stuk_places', as: 'stuk_places'

  resources :stuk_todo_tasks do
    member do
      put :change
    end
  end

  resources :stuk_books
  get 'estuk_dashboard' => 'pages#estuk_dashboard'
  post '/buy/:slug', to: 'estuk_transactions#create', as: :buy
  get '/pickup/:guid', to: 'estuk_transactions#pickup', as: :pickup
  
  resources :stuk_starter_projects do
    resources :stuk_starter_rewards, only: [:new, :create, :edit, :update, :destroy]
    resources :stuk_starter_pledges
    resources :stuk_starter_payments, only: [:new, :create]
  end

  resources :places
  resources :places_reviews
  get 'stuk_places_dashboard' => 'pages#stuk_places_dashboard'

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to_home_brand(controller.controller_name)
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav.navbar-right
        - if current_user
          - if controller.controller_name == 'stuk_books'
            li = link_to 'Books', stuk_books_path
            li = link_to 'Dashboard', estuk_dashboard_path
          - elsif controller.controller_name == 'stuk_starters'
            li = link_to 'Start a project', new_stuk_starter_project_path
          - elsif controller.controller_name == 'places'
            li = link_to 'Dashboard', stuk_places_dashboard_path
          li = link_to 'Edit profile', edit_user_registration_path
          li = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          li = link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Rangki Portfolio
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / script[type="text/javascript" src="https://js.braintreegateway.com/v2/braintree.js"]
    script[async defer src="https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API']}&callback=initMap"]
  body

    = render 'layouts/header'

    - flash.each do |type, message|
      .alert.alert-info.fade-in
        button.close[data-dismiss="alert"] x
        = message
    
    div class=(current_page?(stuk_places_path) ? 'landing' : 'container')
      = yield